<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>8.0</LangVersion>
    <ASCOM_COMPONENT_PATH Condition="'$(ASCOM_ROOT)' != ''">$(ASCOM_ROOT)</ASCOM_COMPONENT_PATH>
    <ASCOM_COMPONENT_PATH Condition="'$(ASCOM_COMPONENT_PATH)' == ''">C:\Program Files (x86)\ASCOM\Developer\Components\Platform</ASCOM_COMPONENT_PATH>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DarkLightDriver\DarkLightDriver.csproj" />
    <Reference Include="ASCOM.DeviceInterfaces">
      <HintPath>$(ASCOM_COMPONENT_PATH)\ASCOM.DeviceInterfaces.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
</Project>
